Modify files for desktop version of mobile portfolio
tahseenzahra/Portfolio-setup-and-mobile-version-skeleton pull request #10
Opened 2022-05-06 14:41 UTC by tahseenzahra

This branch contains:
- organized files of CSS
- desktop portfolio code
- transition to buttons

2022-05-06 15:36 UTC, gtekle requested changes
Hi @tahseenzahra :wave:,  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![this-close](https://user-images.githubusercontent.com/44057863/167165347-3af359cf-f776-442d-970d-9b6db2bfd7e5.gif)


## Highlights
:heavy_check_mark: Well organized code and files
:heavy_check_mark: Professional documentation
:heavy_check_mark: Nice UI design

## Required Changes ♻️
_Check the comments under the review._

- [x] Kindly use the left alignment of the headline social media icons as in the figma design.
#### Figma
![headline-works-section-figma](https://user-images.githubusercontent.com/44057863/167164707-5c435b7e-6e84-4f19-b3b3-7ff9ff4c1d03.png)
#### Impl
![headline-works-section-impl](https://user-images.githubusercontent.com/44057863/167164726-8073afc0-6294-404f-bb55-5aa467ffa764.png)

- [x] The contents of the project cards are aligned bottom (flex-end) in the figma design. Kindly rectify.
#### Figma
![project-card-desk-figma](https://user-images.githubusercontent.com/44057863/167164977-b6f30b53-a03b-49cd-96f1-b475350fd73f.png)
#### Impl
![project-card-desk-impl](https://user-images.githubusercontent.com/44057863/167165009-3e5c6e73-770c-45d4-bd81-f78d51e1616b.png)

- [x] You should align left the languages, Frameworks and skills list as in the Figma design.
#### Figma
![languages-section--figma](https://user-images.githubusercontent.com/44057863/167165229-b60e3399-e49d-40d3-990f-c7a8373ace27.png)

#### Impl
![languages-section--impl](https://user-images.githubusercontent.com/44057863/167165248-e6cedc5f-9f3a-40ef-844c-587a8cef8124.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 09:26 UTC, zieeco requested changes
Hi @tahseenzahra 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 09:26 UTC, zieeco commented on index.html
> -      </ul>
**[REQUIRED CHANGES]**

- [ ] Hey, as required by the previous review, Please kindly align your list items to the left to be on same line with the paragraph and header content below: 

**YOUR DESIGN** :point_down: 
![align](https://user-images.githubusercontent.com/59397159/167247650-6c863229-0e79-4bd5-9275-a3bbdba38ce1.png)

**FIGMA DESIGN** :point_down: 


![figma](https://user-images.githubusercontent.com/59397159/167247718-79d97568-21f9-440a-a73b-ba093edd84d9.png)

2022-05-07 09:26 UTC, zieeco commented on index.html
>          method="POST"
- [ ] **[OPTIONAL]**
- Although the previous reviewer didn't point this out, however, consider them as **MANDATORY REQUIREMENT** for this project, try addressing them in your spare time..

- Kindly reduce the width of your paragraph and align the button to the left on the form
**YOUR DESIGN** :point_down: 

![FORM](https://user-images.githubusercontent.com/59397159/167248070-5b528a6c-2f92-4600-a01a-f9057783c2f3.png)


**FIGMA DESIGN** :point_down: 

![FORMS](https://user-images.githubusercontent.com/59397159/167248092-e12da1c2-6a8f-4e14-9fc2-f2cbecc76531.png)

2022-05-07 17:21 UTC, m05e5 commented
Hello

2022-05-07 17:26 UTC, m05e5 approved these changes
# Hi @tahseenzahra , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 19:09 UTC, merged