Contact form and its styling
tahseenzahra/Portfolio-setup-and-mobile-version-skeleton pull request #3
Opened 2022-04-27 09:30 UTC by tahseenzahra

This branch contains the contact form in the portfolio.

2022-04-28 09:11 UTC, zainsadaqat requested changes
# Hello Team! 😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 
# 👏🏻 👏🏻 👏🏻 

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +        I'm always interested in hearing about new projects, so if you'd like to
#### According to Figma design, this paragraph should be center-aligned. Also, please replace `<div>` tag with `<p>` as you know it's a paragraph and it should be written in `<p>` tag.

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +          placeholder="Full Name"
#### This input field is required. Please add the required attribute

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +          placeholder="Email Address"
#### This input field is required. Please add the required attribute

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +          class="formTxtArea"
#### This input field is required. Please add the required attribute

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +          class="no-outline"
Kindly add some bottom padding to make it look clean and near to the required Figma design.

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +          class="no-outline"
Kindly add some bottom padding to make it look clean and near to the required Figma design.

2022-04-28 09:11 UTC, zainsadaqat commented on index.html
> +        Enter text here.</textarea
#### Please add a placeholder for `<textarea>` instead of hard-coded text 👍🏻

2022-04-28 11:35 UTC, xtrahuman requested changes
Hello @tahseenzahra, 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] clean and organized code

## Required Changes ♻️
_Check the comments under the review._ ⬇️ ⬇️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 11:35 UTC, xtrahuman commented on index.html
>          <button type="button" class="PrjBTN SePrjBTN Interfont">
Your form is currently not making a post request or submitting, try changing the type button to type submit, It probably might fix the issue.

2022-04-28 11:35 UTC, xtrahuman commented on index.html
> +      <p class="Interfont footerTxt">
Nice job implementing the changes, though I noticed the text is no longer in the center of the page, you can apply `width: 100% `and `text-align: center` to your `p`  to fix

This is how your text current appears. kindly fix as suggested

![image](https://user-images.githubusercontent.com/43564324/165742558-27f44955-ea3a-4417-988d-f0d9a1e0679a.png)

2022-04-28 13:39 UTC, gtekle approved these changes
Hi **@TEAM**, 
# STATUS: APPROVED :clap: :clap: 🎉 🎉 🎉 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![clap-clapping](https://user-images.githubusercontent.com/44057863/165765117-3efd95e8-462b-43e5-95ce-b94ba3ae1fdc.gif)


## Highlights
:heavy_check_mark: Good use of Github flow
:heavy_check_mark: Meaningful commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 13:39 UTC, gtekle commented on README.md
> +👤 **Author**
- [ Optional ] You should use the actual name of the author on behalf of the placeholder text (**Author**)

2022-04-28 13:39 UTC, gtekle commented on index.html
> +        <button type="submit" class="PrjBTN SePrjBTN Interfont">
- [ Optional ] You should align this button horizontally to center as in the figma design.

2022-04-28 14:18 UTC, merged

2022-05-04 07:53 UTC, thecodechaser reviewed
## Hi @tahseenzahra, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the PR is already approved and merged please create a new PR with all the changes. Good luck 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._